- script@1:
    title: Switch Java Version
    inputs:
      - content: |
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          java -version
